export const tokens = {
  page: {
    minHeight: "100vh",
    background: "#100D0A",
    padding: "48px 24px",
    boxSizing: "border-box",
    fontFamily: "'Inter', system-ui, -apple-system, sans-serif",
    position: "relative",
    overflow: "hidden",
  },
  glow: {
    position: "absolute",
    top: -180,
    left: "50%",
    transform: "translateX(-50%)",
    width: 900,
    height: 500,
    background:
      "radial-gradient(closest-side, rgba(76,154,106,0.14), transparent 70%)",
    pointerEvents: "none",
  },
  wrap: { maxWidth: 960, margin: "0 auto", position: "relative" },

  header: { marginBottom: 32 },
  eyebrow: {
    display: "inline-block",
    fontSize: 11,
    fontWeight: 700,
    letterSpacing: "0.14em",
    textTransform: "uppercase",
    color: "#4C9A6A",
    marginBottom: 12,
  },
  title: {
    fontFamily: "'Georgia', 'Iowan Old Style', ui-serif, serif",
    fontSize: 40,
    fontWeight: 600,
    color: "#F5EFE4",
    margin: "0 0 12px",
    letterSpacing: "-0.01em",
  },
  lede: {
    fontSize: 15,
    color: "#A79C89",
    margin: "0 0 24px",
    lineHeight: 1.65,
    maxWidth: 620,
  },
  code: {
    fontFamily: "ui-monospace, 'SF Mono', Menlo, monospace",
    background: "#1F1A14",
    border: "1px solid #2E2820",
    padding: "2px 7px",
    borderRadius: 6,
    fontSize: 12.5,
    color: "#6BB585",
    fontWeight: 600,
    whiteSpace: "nowrap",
    display: "inline-block",
  },
  divider: {
    height: 1,
    background: "linear-gradient(90deg, #2E2820, transparent 70%)",
    margin: "0 0 12px",
  },

  toolbar: {
    display: "flex",
    justifyContent: "space-between",
    alignItems: "center",
    flexWrap: "wrap",
    gap: 16,
    marginBottom: 24,
  },
  searchGroup: { display: "flex", gap: 8, flexWrap: "wrap" },

  searchBtn: {
    padding: "8px 16px",
    borderRadius: 9999,
    border: "1px solid #2E2820",
    background: "#41674f",
    color: "#F5EFE4",
    fontSize: 14,
    cursor: "pointer",
    fontWeight: 500,
  },

  indexBtn: {
    padding: "8px 16px",
    borderRadius: 9999,

    fontSize: 14,
    cursor: "pointer",
    fontWeight: 500,
  },
  indexBtnOn: {
    border: "1px solid #2E2820",
    background: "#6BB585",
    color: "#2E2820",
  },
  indexBtnOff: {
    border: "1px solid #6BB585",
    background: "#2E2820",
    color: "#6BB585",
  },

  input: {
    padding: "8px 32px 8px 14px",
    borderRadius: 10,
    border: "1px solid #2E2820",
    background: "#161210",
    fontSize: 14,
    color: "#6BB585",
    cursor: "pointer",
    fontWeight: 500,
    appearance: "none",
    WebkitAppearance: "none",
    MozAppearance: "none",
  },

  metaRow: { minHeight: 20, marginBottom: 16 },
  count: {
    fontSize: 13,
    color: "#7A705F",
    fontWeight: 500,
    margin: 0,
    letterSpacing: "0.02em",
  },
  empty: {
    gridColumn: "1 / -1",
    textAlign: "center",
    padding: "48px 16px",
    background: "#161210",
    borderRadius: 16,
    border: "1px dashed #3D362B",
  },
  errorBox: {
    background: "rgba(201, 82, 74, 0.1)",
    border: "1px solid rgba(201, 82, 74, 0.35)",
    borderRadius: 12,
    padding: "16px",
    color: "#E29A93",
    fontSize: 14,
    marginBottom: 24,
  },

  grid: {
    display: "grid",
    gridTemplateColumns: "repeat(auto-fill, minmax(280px, 1fr))",
    gap: 20,
    marginBottom: 40,
  },

  card: {
    background: "#161210",
    borderRadius: 16,
    border: "1px solid #241F19",
    overflow: "hidden",
    boxShadow: "0 1px 3px rgba(0, 0, 0, 0.4)",
    display: "flex",
    flexDirection: "column",
  },
  cardImg: {
    background: "linear-gradient(160deg, #1B1712 0%, #14100D 100%)",
    height: 120,
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    borderBottom: "1px solid #221C15",
  },
  cardBody: {
    padding: "20px",
    flexGrow: 1,
    display: "flex",
    flexDirection: "column",
  },
  cardName: {
    fontFamily: "'Georgia', ui-serif, serif",
    fontSize: 17,
    fontWeight: 600,
    color: "#F2ECE1",
    margin: "0 0 14px",
    lineHeight: 1.3,
  },
  priceRow: {
    marginTop: "auto",
    display: "flex",
    alignItems: "baseline",
    gap: 8,
  },
  priceDots: {
    flexGrow: 1,
    borderBottom: "1px dashed #3D362B",
    marginBottom: 4,
  },
  cardPrice: {
    fontSize: 16,
    color: "#6BB585",
    margin: 0,
    fontWeight: 700,
    fontVariantNumeric: "tabular-nums",
  },

  pagination: {
    display: "flex",
    justifyContent: "center",
    alignItems: "center",
    gap: 8,
    flexWrap: "wrap",
    marginTop: 16,
  },
  pageBtn: {
    minWidth: 40,
    height: 40,
    padding: "0 14px",
    borderRadius: 10,
    border: "1px solid #2E2820",
    background: "#161210",
    color: "#D8CFC0",
    fontSize: 14,
    cursor: "pointer",
    fontWeight: 600,
  },
  pageBtnActive: {
    background: "#4C9A6A",
    color: "#100D0A",
    borderColor: "#4C9A6A",
    boxShadow: "0 4px 14px rgba(76, 154, 106, 0.22)",
  },
  pageBtnDisabled: {
    background: "#131110",
    color: "#4A4438",
    borderColor: "#221C15",
    cursor: "not-allowed",
  },
};
